[platformio]
default_envs = disco_f429zi_20k_50_700ns

[env]
platform = ststm32
board = disco_f429zi
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
build_flags =
  -D PWM_FREQUENCY_HZ=20000UL

[env:disco_f429zi_20k_50_700ns]
build_flags =
  ${env.build_flags}
  -D PWM_DUTY_PERMILLE=500UL
  -D PWM_DEADTIME_NS=700UL

[env:disco_f429zi_20k_50_600ns]
build_flags =
  ${env.build_flags}
  -D PWM_DUTY_PERMILLE=500UL
  -D PWM_DEADTIME_NS=600UL

[env:disco_f429zi_20k_50_800ns]
build_flags =
  ${env.build_flags}
  -D PWM_DUTY_PERMILLE=500UL
  -D PWM_DEADTIME_NS=800UL

[env:disco_f429zi_20k_5_700ns]
build_flags =
  ${env.build_flags}
  -D PWM_DUTY_PERMILLE=50UL
  -D PWM_DEADTIME_NS=700UL

[env:disco_f429zi_20k_25_700ns]
build_flags =
  ${env.build_flags}
  -D PWM_DUTY_PERMILLE=250UL
  -D PWM_DEADTIME_NS=700UL

[env:disco_f429zi_20k_75_700ns]
build_flags =
  ${env.build_flags}
  -D PWM_DUTY_PERMILLE=750UL
  -D PWM_DEADTIME_NS=700UL

[env:disco_f429zi_20k_95_700ns]
build_flags =
  ${env.build_flags}
  -D PWM_DUTY_PERMILLE=950UL
  -D PWM_DEADTIME_NS=700UL
